stages:
  - build
  - test
  - build-image
  - deploy
cache:
  paths:
    - .cache/pip
    - venv/
variables:
  HEROKU_APP: svelte-template
  HEROKU_API_KEY: cb15a5a6-1baf-4078-b424-11182bc2d124


build image:
    image: node:16-alpine
    stage: build
    script:
        - npm install
        - npm run build



build-image-job:
    image: docker:latest
    stage: deploy
    services:
        - docker:dind
    before_script:
        - apk add curl nodejs bash
        - curl https://cli-assets.heroku.com/install.sh | sh
        - ln -s /usr/local/bin/heroku /usr/bin/heroku
    script:
        - heroku container:login
        - heroku container:push --app svelte-template web
        - heroku container:release --app svelte-template web
